# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(default=None, to='comics.Category'),
        ),
    ]
